# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/slzatz/listmanager_c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/slzatz/listmanager_c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/slzatz/listmanager_c/CMakeFiles /home/slzatz/listmanager_c/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/slzatz/listmanager_c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named listmanager_term_improved_cpp

# Build rule for target.
listmanager_term_improved_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 listmanager_term_improved_cpp
.PHONY : listmanager_term_improved_cpp

# fast build rule for target.
listmanager_term_improved_cpp/fast:
	$(MAKE) -f CMakeFiles/listmanager_term_improved_cpp.dir/build.make CMakeFiles/listmanager_term_improved_cpp.dir/build
.PHONY : listmanager_term_improved_cpp/fast

listmanager_term_improved.o: listmanager_term_improved.cpp.o

.PHONY : listmanager_term_improved.o

# target to build an object file
listmanager_term_improved.cpp.o:
	$(MAKE) -f CMakeFiles/listmanager_term_improved_cpp.dir/build.make CMakeFiles/listmanager_term_improved_cpp.dir/listmanager_term_improved.cpp.o
.PHONY : listmanager_term_improved.cpp.o

listmanager_term_improved.i: listmanager_term_improved.cpp.i

.PHONY : listmanager_term_improved.i

# target to preprocess a source file
listmanager_term_improved.cpp.i:
	$(MAKE) -f CMakeFiles/listmanager_term_improved_cpp.dir/build.make CMakeFiles/listmanager_term_improved_cpp.dir/listmanager_term_improved.cpp.i
.PHONY : listmanager_term_improved.cpp.i

listmanager_term_improved.s: listmanager_term_improved.cpp.s

.PHONY : listmanager_term_improved.s

# target to generate assembly for a file
listmanager_term_improved.cpp.s:
	$(MAKE) -f CMakeFiles/listmanager_term_improved_cpp.dir/build.make CMakeFiles/listmanager_term_improved_cpp.dir/listmanager_term_improved.cpp.s
.PHONY : listmanager_term_improved.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... listmanager_term_improved_cpp"
	@echo "... edit_cache"
	@echo "... listmanager_term_improved.o"
	@echo "... listmanager_term_improved.i"
	@echo "... listmanager_term_improved.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

